<?php
/**
 * OfferApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UrbanDiscovery
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use Swagger\Server\Model\Offer;

/**
 * OfferApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  Swagger\Server\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
interface OfferApiInterface
{

    /**
     * Sets authentication method api_key
     *
     * @param string $value Value of the api_key authentication method.
     *
     * @return void
     */
    public function setapi_key($value);

    /**
     * Operation addOffer
     *
     * Add a new offer
     *
     * @param  Swagger\Server\Model\Offer $body  Offer object that needs to be added (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function addOffer(Offer $body, &$responseCode, array &$responseHeaders);

    /**
     * Operation deleteOffer
     *
     * Deletes a offer
     *
     * @param  int $offerId  Offer id to delete (required)
     * @param  string $apiKey   (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function deleteOffer($offerId, $apiKey = null, &$responseCode, array &$responseHeaders);

    /**
     * Operation findOffersByUser
     *
     * Finds Offer by user
     *
     * @param  int $userid  Status values that need to be considered for filter (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Swagger\Server\Model\Offer[]
     *
     */
    public function findOffersByUser($userid, &$responseCode, array &$responseHeaders);


    /**
     * Operation findOffersByCoordinates
     *
     * Finds Offer by Coordinates
     *
     * @param  int $coordinates  Coodinates of the current position (required)
     * @param  int $distance  Maximum distance to an offer (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Swagger\Server\Model\Offer[]
     *
     */
    public function findOffersByCoordinates($coordinates, $distance, &$responseCode, array &$responseHeaders);

    /**
     * Operation getOfferById
     *
     * Find offer by ID
     *
     * @param  int $offerId  ID of the offer to return (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Swagger\Server\Model\Offer[]
     *
     */
    public function getOfferById($offerId, &$responseCode, array &$responseHeaders);
}
