<?php
/**
 * User
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UrbanDiscovery
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the User model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class User 
{
        /**
     * @var int|null
     * @SerializedName("id")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $id;

    /**
     * @var string|null
     * @SerializedName("username")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $username;

    /**
     * @var string|null
     * @SerializedName("firstname")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $firstname;

    /**
     * @var string|null
     * @SerializedName("name")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $name;

    /**
     * @var string|null
     * @SerializedName("address")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $address;

    /**
     * @var string|null
     * @SerializedName("zip")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $zip;

    /**
     * @var string|null
     * @SerializedName("city")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $city;

    /**
     * @var string|null
     * @SerializedName("coordinates")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $coordinates;

    /**
     * @var string|null
     * @SerializedName("email")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $email;

    /**
     * @var string|null
     * @SerializedName("password")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $password;

    /**
     * @var string|null
     * @SerializedName("phone")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $phone;

    /**
     * @var string|null
     * @SerializedName("forgot_pw")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $forgotPw;

    /**
     * @var string|null
     * @SerializedName("forgot_pw_time")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $forgotPwTime;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->id = isset($data['id']) ? $data['id'] : null;
        $this->username = isset($data['username']) ? $data['username'] : null;
        $this->firstname = isset($data['firstname']) ? $data['firstname'] : null;
        $this->name = isset($data['name']) ? $data['name'] : null;
        $this->address = isset($data['address']) ? $data['address'] : null;
        $this->zip = isset($data['zip']) ? $data['zip'] : null;
        $this->city = isset($data['city']) ? $data['city'] : null;
        $this->coordinates = isset($data['coordinates']) ? $data['coordinates'] : null;
        $this->email = isset($data['email']) ? $data['email'] : null;
        $this->password = isset($data['password']) ? $data['password'] : null;
        $this->phone = isset($data['phone']) ? $data['phone'] : null;
        $this->forgotPw = isset($data['forgotPw']) ? $data['forgotPw'] : null;
        $this->forgotPwTime = isset($data['forgotPwTime']) ? $data['forgotPwTime'] : null;
    }

    /**
     * Gets id.
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param int|null $id
     *
     * @return $this
     */
    public function setId($id = null)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets username.
     *
     * @return string|null
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Sets username.
     *
     * @param string|null $username
     *
     * @return $this
     */
    public function setUsername($username = null)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Gets firstname.
     *
     * @return string|null
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Sets firstname.
     *
     * @param string|null $firstname
     *
     * @return $this
     */
    public function setFirstname($firstname = null)
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Gets name.
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Sets name.
     *
     * @param string|null $name
     *
     * @return $this
     */
    public function setName($name = null)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Gets address.
     *
     * @return string|null
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Sets address.
     *
     * @param string|null $address
     *
     * @return $this
     */
    public function setAddress($address = null)
    {
        $this->address = $address;

        return $this;
    }

    /**
     * Gets zip.
     *
     * @return string|null
     */
    public function getZip()
    {
        return $this->zip;
    }

    /**
     * Sets zip.
     *
     * @param string|null $zip
     *
     * @return $this
     */
    public function setZip($zip = null)
    {
        $this->zip = $zip;

        return $this;
    }

    /**
     * Gets city.
     *
     * @return string|null
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Sets city.
     *
     * @param string|null $city
     *
     * @return $this
     */
    public function setCity($city = null)
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Gets coordinates.
     *
     * @return string|null
     */
    public function getCoordinates()
    {
        return $this->coordinates;
    }

    /**
     * Sets coordinates.
     *
     * @param string|null $coordinates
     *
     * @return $this
     */
    public function setCoordinates($coordinates = null)
    {
        $this->coordinates = $coordinates;

        return $this;
    }

    /**
     * Gets email.
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Sets email.
     *
     * @param string|null $email
     *
     * @return $this
     */
    public function setEmail($email = null)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Gets password.
     *
     * @return string|null
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Sets password.
     *
     * @param string|null $password
     *
     * @return $this
     */
    public function setPassword($password = null)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Gets phone.
     *
     * @return string|null
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Sets phone.
     *
     * @param string|null $phone
     *
     * @return $this
     */
    public function setPhone($phone = null)
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * Gets forgotPw.
     *
     * @return string|null
     */
    public function getForgotPw()
    {
        return $this->forgotPw;
    }

    /**
     * Sets forgotPw.
     *
     * @param string|null $forgotPw
     *
     * @return $this
     */
    public function setForgotPw($forgotPw = null)
    {
        $this->forgotPw = $forgotPw;

        return $this;
    }

    /**
     * Gets forgotPwTime.
     *
     * @return string|null
     */
    public function getForgotPwTime()
    {
        return $this->forgotPwTime;
    }

    /**
     * Sets forgotPwTime.
     *
     * @param string|null $forgotPwTime
     *
     * @return $this
     */
    public function setForgotPwTime($forgotPwTime = null)
    {
        $this->forgotPwTime = $forgotPwTime;

        return $this;
    }
}


